smp.AddressBookDemo/smp.AddressBookDemo.Web/Controllers/CompaniesController.cs
using System;
using System.Web.Mvc;
using smp.AddressBookDemo.Models.Input;
using smp.AddressBookDemo.Repository;
using smp.AddressBookDemo.Web.Filters;

namespace smp.AddressBookDemo.Web.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ICompanyRepository _repository;

        public CompaniesController(ICompanyRepository repository)
        {
            _repository = repository;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult NameStarting(string id)
        {
            var data = _repository.GetCompaniesByFirstLetter(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [GuidId]
        public ActionResult Detail(Guid id)
        {
            var data = _repository.GetCompany(id);
            return View(data);
        }

        [HttpGet]
        public ActionResult AddNew()
        {
            var newId = _repository.AddNew();
            return Json(newId, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Save(CompanyDetailsInput model)
        {
            var result = _repository.Save(model);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

smp.AddressBookDemo/smp.AddressBookDemo.Web/Views/Companies/Detail.cshtml
@model smp.AddressBookDemo.Models.View.CompanyView

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="companyContainer">
    <div>
        <legend id="detailsTitle" class="collapsibleLegend">@Model.Name <i class="icon-chevron-down hide"></i></legend>
        <div>
            <div class="form-actions">
                <button class="btn btn-success" type="button" data-bind="visible: DisplayCompany, click: EditCompany">Edit</button>
                <button class="btn btn-danger" type="button" data-bind="visible: EditingCompany, click: CancelEditCompany">Cancel</button>
                <button class="btn btn-success" type="button" data-bind="visible: EditingCompany, click: SaveCompany">Save Changes</button>
                <span id="SavedDetails" class="text-success hide">Saved</span>
            </div>
            <div class="form-horizontal span5">
                <div class="control-group">
                    <label class="control-label" for="Name">
                        Name</label>
                    <div class="controls">
                        <input  type="text" data-bind="value: Name, visible: EditingCompany" />
                        <span data-bind="text: Name, visible: DisplayCompany"></span>
                    </div>
                </div>
        
                <div class="control-group">
                    <label class="control-label" for="RegistrationNumber">
                        Registration Number</label>
                    <div class="controls">
                        <input  type="text" data-bind="value: RegistrationNumber, visible: EditingCompany" />
                        <span data-bind="text: RegistrationNumber, visible: DisplayCompany"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="Telephone">
                        Telephone</label>
                    <div class="controls">
                        <input  type="text" data-bind="value: Telephone, visible: EditingCompany" />
                        <span data-bind="text: Telephone, visible: DisplayCompany"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="Name">
                        Name</label>
                    <div class="controls">
                        <input  type="text" data-bind="value: Email, visible: EditingCompany" />
                        <span data-bind="text: Email, visible: DisplayCompany"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="WebSite">
                        WebSite</label>
                    <div class="controls">
                        <input  type="text" data-bind="value: WebSite, visible: EditingCompany" />
                        <span data-bind="text: WebSite, visible: DisplayCompany"></span>
                    </div>
                </div>
            </div>
            <div class="form-horizontal span5">
                <div class="control-group">
                    <label class="control-label" for="PostCode">
                        PostCode</label>
                    <div class="controls">
                        <input  type="text" data-bind="value: PostCode, visible: EditingCompany" />
                        <button class="btn btn-info" type="button" data-bind="click: SearchPostCode, visible: EditingCompany">Search</button>
                        <span data-bind="text: PostCode, visible: DisplayCompany"></span>
                    </div>
                </div>
        
                <div class="control-group">
                    <label class="control-label" for="AddressLine1">
                        Address Line 1</label>
                    <div class="controls">
                        <input  type="text" data-bind="value: AddressLine1, visible: EditingCompany" />
                        <span data-bind="text: AddressLine1, visible: DisplayCompany"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="AddressLine2">
                        Address Line 2</label>
                    <div class="controls">
                        <input  type="text" data-bind="value: AddressLine2, visible: EditingCompany" />
                        <span data-bind="text: AddressLine2, visible: DisplayCompany"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="Town">
                        Town</label>
                    <div class="controls">
                        <input  type="text" data-bind="value: Town, visible: EditingCompany" />
                        <span data-bind="text: Town, visible: DisplayCompany"></span>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="County">
                        County</label>
                    <div class="controls">
                        <input  type="text" data-bind="value: County, visible: EditingCompany" />
                        <span data-bind="text: County, visible: DisplayCompany"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <legend class="collapsibleLegend">Contacts <i class="icon-chevron-down hide"></i></legend>
        <div>
            <table class="table table-striped table-bordered table-hover" data-bind="foreach: Contacts">
                <tr>
                    <td>
                        <p>
                            <strong>Name : </strong>
                            <span data-bind="text: Title"> </span><span data-bind="text: FirstName"> </span><span data-bind="text: LastName"> </span> (<span data-bind="text: CompanyPosition"></span>)
                        </p>
                        <p>
                            <strong>Contact : </strong>
                            <span data-bind="text: PhoneNumber"></span> - <span data-bind="text: Email"></span>
                        </p>
                        <div class="pull-right">
                            <button class="btn btn-success" type="button">Edit</button>
                            <button class="btn btn-danger" type="button">Remove</button>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    app.company.init(@Html.Raw(Json.Encode(Model)));
</script>

smp.AddressBookDemo/smp.AddressBookDemo.Web/Views/Companies/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="companiesContainer" class="row-fluid">
    <div class="row-fluid">
        <div class="pagination">
            <ul data-bind="foreach: FirstLetters">
                <li><a href="#" data-bind="text: letter, click: $parent.SelectLetter"></a></li>
            </ul>
        </div>
    </div>
    <div class="form-actions">
        <button class="btn btn-success" type="button" data-bind="click: AddNewCompany">Add Company</button>
        <div class="pull-right">
            Matching companies : <span data-bind="text: Count"></span>
        </div>
    </div>
    <div class="row-fluid">
        
        <table class="table table-hover table-striped table-bordered" data-bind="foreach: Companies">
            <td data-bind="click: $parent.SelectCompany">
                <div>
                    <p><strong data-bind="text: Name"></strong></p>
                    <p><span data-bind="text: Town"></span> (<span data-bind="text: PostCode"></span>)</p> 
                </div>
            </td>
        </table>
    </div>
</div>

<script type="text/javascript">
    app.Companies.init();
</script>

smp.AddressBookDemo/smp.AddressBookDemo.Web/Views/Shared/_Layout.cshtml
@{
    
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
    <title>smp Demo Address Book</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")"  rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-responsive.min.css")"  rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-2.0.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/knockout-2.2.1.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/knockout.mapping-latest.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/App/app.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/App/Companies.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/App/company.js")" type="text/javascript"></script>
    
</head>

    <body>
        <div id="errorModal" class="modal hide fade alert alert-block alert-error">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;</button>
                <h3 id="errorTitle">
                </h3>
            </div>
            <div class="modal-body">
                <p id="ErrorMessage">
                </p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-danger" data-dismiss="modal">Close</a>
            </div>
        </div>
        
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <div>
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".masterCollapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>

                        <div>
                            <a class="brand" href="@Url.Action("Index", "Companies")">Demo Address Book</a>
                        </div>

                        <div class="nav-collapse collapse masterCollapse">
                            <ul class="nav">
                                <li>
                                    <a href="@Url.Action("Index", "Companies")"><i class="icon-home"></i>Home</a>
                                </li>
                                <form class="navbar-search pull-right">
                                    <input id="quicksearch" type="text" class="search-query" data-provide="typeahead" placeholder="Find a company">
                                </form>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="page">
            <section id="main">
                @RenderBody()
            </section>
        </div>

    </body>
</html>